from tkinter import *
from tkinter.ttk import Checkbutton

#class checkbox:
  #  def _init_(self, name, state):
       # self.name = name
       # self.state = BooleanVar()
      #  self.state.set(False) # задайте проверку состояния чекбокса

#def set_state(state):
   # name = BooleanVar()
    #name.set(False)


window = Tk()
window.title("Выберите параметры анализа текста")
window.geometry('400x400')
chk_state1 = BooleanVar()
chk_state1.set(False)  # задайте проверку состояния чекбокса
chk1 = Checkbutton(window, text='Выравнивание абзаца', var=chk_state1)
chk1.grid(column=0, row=0)
chk_state2 = BooleanVar()
chk_state2.set(False)
chk2 = Checkbutton(window, text='Отступ перед абзацем(см)', var=chk_state2)
chk2.grid(column=0, row=1)
chk_state3 = BooleanVar()
chk_state3.set(False)
chk3 = Checkbutton(window, text='Отступ после абзаца(см)', var=chk_state3)
chk3.grid(column=0, row=2)
chk_state4 = BooleanVar()
chk_state4.set(False)
chk4 = Checkbutton(window, text='Отступ слева(см)', var=chk_state4)
chk4.grid(column=0, row=3)
chk_state5 = BooleanVar()
chk_state5.set(False)
chk5 = Checkbutton(window, text='Отступ справа(см)', var=chk_state5)
chk5.grid(column=0, row=4)
chk_state6 = BooleanVar()
chk_state6.set(False)
chk6 = Checkbutton(window, text='Отступ первой строки абзаца(см)', var=chk_state6)
chk6.grid(column=0, row=5)
chk_state7 = BooleanVar()
chk_state7.set(False)
chk7 = Checkbutton(window, text='Не отрывать от следующего абзаца', var=chk_state7)
chk7.grid(column=0, row=6)
chk_state8 = BooleanVar()
chk_state8.set(False)
chk8 = Checkbutton(window, text='Не разрывать абзац', var=chk_state8)
chk8.grid(column=0, row=7)
chk_state9 = BooleanVar()
chk_state9.set(False)
chk9 = Checkbutton(window, text='Абзац с новой страницы', var=chk_state9)
chk9.grid(column=0, row=8)
chk_state10 = BooleanVar()
chk_state10.set(False)
chk10 = Checkbutton(window, text='Запрет висячих строк', var=chk_state10)
chk10.grid(column=0, row=9)
chk_state11 = BooleanVar()
chk_state11.set(False)
chk11 = Checkbutton(window, text='Курсивный текст', var=chk_state11)
chk11.grid(column=0, row=10)
chk_state12 = BooleanVar()
chk_state12.set(False)
chk12 = Checkbutton(window, text='Полужирный текст', var=chk_state12)
chk12.grid(column=0, row=11)
chk_state13 = BooleanVar()
chk_state13.set(False)
chk13 = Checkbutton(window, text='Подчёркнутый текст', var=chk_state13)
chk13.grid(column=0, row=12)
chk_state14 = BooleanVar()
chk_state14.set(False)
chk14 = Checkbutton(window, text='Название шрифта', var=chk_state14)
chk14.grid(column=0, row=13)
chk_state15 = BooleanVar()
chk_state15.set(False)
chk15 = Checkbutton(window, text='Размер шрифта(кегль)', var=chk_state15)
chk15.grid(column=0, row=14)
chk_state16 = BooleanVar()
chk_state16.set(False)
chk16 = Checkbutton(window, text='Цвет текста, RGB', var=chk_state16)
chk16.grid(column=0, row=15)
chk_state17 = BooleanVar()
chk_state17.set(False)
chk17 = Checkbutton(window, text='Цвет заливки текста', var=chk_state17)
chk17.grid(column=0, row=16)

#btn = Button(window, text="Начать анализ", command=Tk.destroy())
#btn.grid(column=1, row=0)

window.mainloop()

#import tkinter as tk

#class SwitchApp(tk.Tk):
  #  def __init__(self):
    #    super().__init__()
    #    self.var1 = tk.BooleanVar()
      #  self.var2 = tk.BooleanVar()
      #  self.var3 = tk.BooleanVar()
      #  self.var4 = tk.BooleanVar()
       # self.var5 = tk.BooleanVar()
       # self.var6 = tk.BooleanVar()
       # self.var7 = tk.BooleanVar()
       # self.var8 = tk.BooleanVar()
      #  self.var9 = tk.BooleanVar()
       # self.var10 = tk.BooleanVar()
      #  self.var11 = tk.BooleanVar()
       # self.var12 = tk.BooleanVar()
      #  self.var13 = tk.BooleanVar()
       # self.var14 = tk.BooleanVar()
      #  self.var15 = tk.BooleanVar()
       # self.var16 = tk.BooleanVar()
       # self.var17 = tk.BooleanVar()

      #  self.cb = tk.Checkbutton(self, text="Выравнивание абзаца", variable=self.var1)
    #    self.cb.pack(side=tk.TOP)
     #   self.cb = Checkbutton(self, text='Отступ перед абзацем(см)', variable=self.var1)
      #  self.cb = Checkbutton(self, text='Отступ после абзаца(см)', variable=self.var1)
      #  self.cb = Checkbutton(self, text='Отступ слева(см)', variable=self.var1)
      #  self.cb = Checkbutton(self, text='Отступ справа(см)', variable=self.var1)
       # self.cb = Checkbutton(self, text='Отступ первой строки абзаца(см)', variable=self.var1)
       # self.cb = Checkbutton(self, text='Не отрывать от следующего абзаца', variable=self.var1)
       # self.cb = Checkbutton(self, text='Не разрывать абзац', variable=self.var1)
       # self.cb = Checkbutton(self, text='Абзац с новой страницы', variable=self.var1)
       # self.cb = Checkbutton(self, text='Запрет висячих строк', variable=self.var1)
      #  self.cb = Checkbutton(self, text='Курсивный текст', variable=self.var1)
      #  self.cb = Checkbutton(self, text='Полужирный текст', variable=self.var1)
      #  self.cb = Checkbutton(self, text='Подчёркнутый текст', variable=self.var1)
      #  self.cb = Checkbutton(self, text='Название шрифта', variable=self.var1)
      #  self.cb = Checkbutton(self, text='Размер шрифта(кегль)', variable=self.var1)
      #  self.cb = Checkbutton(self, text='Цвет текста, RGB', variable=self.var1)
      #  self.cb = Checkbutton(self, text='Цвет заливки текста', variable=self.var1)
   # def print_value(self):
     #   print(self.var.get())

#if __name__ == "__main__":
  #  app = SwitchApp()
   # app.mainloop()